In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [42]:
df = pd.DataFrame()
for i in tqdm(range(174)):
    sub = pd.read_excel('DATA/CT_Data_Original.xlsx', usecols=np.arange(3*i, 3*i+3))
    col = sub.columns
    sub = sub.rename(columns={col[0]: 'Date', col[2]: col[1]+'_POS'})
    sub = sub[pd.notnull(sub.Date)]
    sub = sub.set_index('Date')
    if i == 0:
        df = sub
    else:
        df = pd.merge(df, sub, left_index=True, right_index=True, how='outer')
df.to_excel('CT_DATA.xlsx')

100%|████████████████████████████████████████████████████████████████████████████████| 174/174 [05:26<00:00,  1.88s/it]

In [43]:
df

,UXF07,UXF07_POS,UXG07,UXG07_POS,UXH07,UXH07_POS,UXJ07,UXJ07_POS,UXK07,UXK07_POS,...,UXG1,UXG1_POS,UXH1,UXH1_POS,UXJ1,UXJ1_POS,UXK1,UXK1_POS,UXM1,UXM1_POS
Date,,,,,,,,,,,,,,,,,,,,,
2006-03-09,NaN,NaN,16.04,35.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-03-10,NaN,NaN,16.13,39.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-03-13,NaN,NaN,16.13,39.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-03-14,NaN,NaN,16.11,39.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-03-15,NaN,NaN,16.09,39.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-10-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.975,18079.0,29.025,9856.0,28.425,2222.0,28.000,465.0,26.025,6.0
2020-10-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.725,17790.0,28.825,9961.0,28.300,2350.0,27.850,470.0,26.375,6.0
2020-10-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28.925,17914.0,28.325,10161.0,27.875,2486.0,27.475,477.0,27.475,7.0
2020-10-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.950,18011.0,27.625,10198.0,27.275,2629.0,26.825,502.0,26.825,7.0
2020-10-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN